---
- hosts: 127.0.0.1
  connection: local
  user: pi
  become: true
  become_user: root
  tasks:
    - name: Ensure /var/www/html/scripts/ exist
      file:
        path: /var/www/html/scripts/
        state: directory
        recurse: yes
        owner: www-data
        group: www-data
        mode: 0755
    - name: Uploading radio script files to /var/www/html/scripts/
      copy:
        src: "{{ item }}"
        dest: /var/www/html/scripts/
        owner: root
        group: root
        mode: 0755
      with_fileglob:
        - "varwwwhtml/scripts/*.sh"
    - name: Uploading radio web files to /var/www/html
      copy:
        src: "{{ item }}"
        dest: /var/www/html/
        owner: www-data
        group: www-data
        mode: 0644
      with_fileglob:
        - "varwwwhtml/*"
    # _station
    - name: Check if config file _station exist
      stat:
        path: /var/www/html/scripts/config/_station
      register: _station_result
    - name: Uploading config file _station
      copy:
        src: "{{ item }}"
        dest: /var/www/html/config/
        owner: www-data
        group: www-data
        mode: 0644
      with_fileglob:
        - "varwwwhtml/config/_station"
      when: _station_result.stat.exists == False
    # _stationLast
    - name: Check if config file _stationLast exist
      stat:
        path: /var/www/html/scripts/config/_stationLast
      register: _stationLast_result
    - name: Uploading config file _stationLast
      copy:
        src: "{{ item }}"
        dest: /var/www/html/config/
        owner: www-data
        group: www-data
        mode: 0644
      with_fileglob:
        - "varwwwhtml/config/_stationLast"
      when: _stationLast_result.stat.exists == False
    # _volume
    - name: Check if config file _volume exist
      stat:
        path: /var/www/html/scripts/config/_volume
      register: _volume_result
    - name: Uploading config file _volume
      copy:
        src: "{{ item }}"
        dest: /var/www/html/config/
        owner: www-data
        group: www-data
        mode: 0644
      with_fileglob:
        - "varwwwhtml/config/_volume"
      when: _volume_result.stat.exists == False
    # recipients
    - name: Check if config file recipients exist
      stat:
        path: /var/www/html/scripts/config/recipients
      register: recipients_result
    - name: Uploading config file recipients
      copy:
        src: "{{ item }}"
        dest: /var/www/html/config/
        owner: www-data
        group: www-data
        mode: 0644
      with_fileglob:
        - "varwwwhtml/config/recipients"
      when: recipients_result.stat.exists == False

