---
- hosts: 127.0.0.1
  connection: local
  user: pi
  become: true
  become_user: root
  tasks:
    - name: Ensure /usr/local/bin/recipients
      file:
        path: /usr/local/bin/recipients
        owner: pi
        group: pi
        mode: 0644
        state: touch
    - name: Uploading radio scripts to /usr/local/bin
      copy:
        src: "{{ item }}"
        dest: /usr/local/bin/
        owner: root
        group: root
        mode: 0755
      with_fileglob:
        - "usrlocalbin/*.sh"
    - name: Uploading radio web files to /var/www/html
      copy:
        src: "{{ item }}"
        dest: /var/www/html/
        owner: www-data
        group: www-data
        mode: 0644
      with_fileglob:
        - "varwwwhtml/*"
    - name: Creating CRON for Radio Running Check
      cron:
        name: "Radio running check"
        minute: "*/1"
        job: "/usr/local/bin/runRadioIfNotRunning.sh"

