---
- hosts: 127.0.0.1
  connection: local
  user: pi
  become: true
  become_user: root
  tasks:
    - name: Ensure /usr/local/bin/recipients exist
      file:
        path: /usr/local/bin/recipients
        owner: pi
        group: pi
        mode: 0644
        state: touch
    - name: Uploading radio scripts to /usr/local/bin
      copy:
        src: "{{ item }}"
        dest: /usr/local/bin/
        owner: root
        group: root
        mode: 0755
      with_fileglob:
        - "usrlocalbin/*.sh"
    - name: Uploading radio web files to /var/www/html
      copy:
        src: "{{ item }}"
        dest: /var/www/html/
        owner: www-data
        group: www-data
        mode: 0644
      with_fileglob:
        - "varwwwhtml/*"
    - name: Ensure /var/www/html/config/ exist
      file:
        path: /var/www/html/config/
        state: directory
        recurse: yes
        owner: www-data
        group: www-data
        mode: 0755
    - name: Uploading radio config files to /var/www/html/config/
      copy:
        src: "{{ item }}"
        dest: /var/www/html/config/
        owner: www-data
        group: www-data
        mode: 0644
      with_fileglob:
        - "varwwwhtml/config/*"
    - name: Ensure /var/www/html/scripts/ exist
      file:
        path: /var/www/html/scripts/
        state: directory
        recurse: yes
        owner: www-data
        group: www-data
        mode: 0755
    - name: Uploading radio script files to /var/www/html/config/
      copy:
        src: "{{ item }}"
        dest: /var/www/html/scripts/
        owner: www-data
        group: www-data
        mode: 0755
      with_fileglob:
        - "varwwwhtml/scripts/*"

